<?php
namespace PHPAssists\Shared\Entities\Abstracts; 

use PHPAssists\Shared\Core\ClassInvocationProcessor;

/**
 * PHPAssists CommerceTransaction Abstract
 *
 * This class represents individual CommerceTransaction within the PHPAssists framework.
 * It manages information related to CommerceTransactions.
 *
 * @link       https://hexome.com.ar
 * @since      1.0.0
 *
 * @package    PHPAssists
 * @subpackage PHPAssists\Shared\Abstract
 * @author     Hexome Cloud <hi@hexome.cloud>
 */
class AbstractCommerceTransaction extends ClassInvocationProcessor {
    // Properties

    /**
     * Unique identifier for the commerce transaction.
     *
     * @var ?string
     */
    private ?string $id;

    /**
     * Unique identifier for the transaction, typically generated by the payment gateway.
     *
     * @var ?string
     */
    private ?string $transaction_id;

    /**
     * Name of the commerce establishment where the transaction occurred.
     *
     * @var ?string
     */
    private ?string $commerce_name;

    /**
     * Specific location of the commerce establishment where the transaction occurred.
     *
     * @var ?string
     */
    private ?string $commerce_location;

    /**
     * Total amount of the commerce transaction.
     *
     * @var ?float
     */
    private ?float $total_amount;

    /**
     * Constructor for the CommerceTransaction class.
     *
     * @param ?string $id The unique identifier for the commerce transaction.
     * @param ?string $transaction_id The unique transaction identifier.
     * @param ?string $commerce_name The name of the commerce.
     * @param ?string $commerce_location The location of the commerce.
     * @param ?float $total_amount The total amount of the transaction.
     */
    public function __construct($id, $transaction_id, $commerce_name, $commerce_location, $total_amount) {
        $this->setId($id);
        $this->setTransactionId($transaction_id);
        $this->setCommerceName($commerce_name);
        $this->setCommerceLocation($commerce_location);
        $this->setTotalAmount($total_amount);
    }
}