name: Code Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PHPUnit and Upload Coverage to Codecov
      run: |
        ./vendor/bin/phpunit --coverage-clover=coverage.xml
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload Codecov configuration
      run: |
        echo "# Global YAML [lower on hierarchy]" >> codecov.yml
        echo "coverage:" >> codecov.yml
        echo "  round: down" >> codecov.yml
        echo "  precision: 5" >> codecov.yml
        echo "" >> codecov.yml
        echo "codecov:" >> codecov.yml
        echo "  branch: stable # set new Default branch" >> codecov.yml

    - name: Commit and push codecov.yml
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add codecov.yml
        git commit -m "Add Codecov configuration"
        git push origin HEAD:main
